name: tests-auth

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7.9.5

      - name: Install dependencies and do Test
        run: |
          cd auth
          pnpm install
          pnpm run test:ci
